---
title: "WOP_2026_trial_setup"
author: "Peter Hyde"
date: "2025-09-25"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE)
```

<br> <br>

### Library

```{r}
library(AlgDesign)
library(tidyverse)
library(readxl)
library(here)

```

<br> <br>

### Import file with genotypes selected

```{r}

accession_plan <- read_excel(here::here("data","WOP_2026_planning.xlsx"),  
                       sheet = "accession_plan") 
accession_plan  
```

<br>

### Format dataframe

```{r}
planning <- accession_plan %>% 
       select(accession_name,nReps,nPlots,category,paired,seedlot_name)

planning
```

### Set up for optBlock
##### 400 plots
##### 8 Blocks
##### Most plot are in pairs mono and inter 
##### One Pea Mono per block
##### Most accessions have 4 plots 2 inter, 2 mono
##### Some accession only have 2 plot 1 inter, 1 mono


```{r}

nBlks <- 8   #8 blocks
nPlotsPerBlk <- 27   #27 pairs, pairing comes in later. This number is a little confussing, I double all the pairs then drop unpaired plots.  In the end each block is not the same number of plots but the same number of pairs or unpaired plots.  


plots <- planning %>% 
  slice(rep(1:n(), times = planning$nReps))  ## increased the  accession to nReps times 

plots

```



### use AlgDesign::optBlock to create the randomization 

```{r}

ss <- floor(runif(1, 10000, 1000000))
set.seed(591742) 




blkOP <- AlgDesign::optBlock(frml=as.formula(~accession_name),
                             withinData=plots,
                             blocksizes=rep(nPlotsPerBlk, nBlks))


# Assemble the design
winterOatDesign<-tibble(accession_name=character())  # create empty dataframe  

for (blockNum in 1:nBlks){
  thisBlock <- as_tibble(blkOP$Blocks[[blockNum]]) %>%
    dplyr::arrange(sample(nrow(blkOP$Blocks[[blockNum]]))) %>%
    dplyr::mutate(block=paste0("Block", blockNum)) %>%
    dplyr::relocate(block, .before=accession_name)
  winterOatDesign <- dplyr::bind_rows(winterOatDesign, thisBlock)
}


winterOatDesign



```


### Make it a planting plan



```{r}

winterOatPea_2026_2 <- winterOatDesign %>% 
  mutate("paired_2" = if_else(paired==0,"single","pair")) %>% 
  mutate(pairNo = seq(1:nrow(winterOatDesign))) %>% 
  mutate(pairs = if_else(paired==0,1,2)) %>% 
  group_by(pairNo)    ## added in some columns identifying pairs and number of pairs

df <- winterOatPea_2026_2 %>% 
  expand(count = seq(1:pairs)) ## create a dataframe doubling the pairs = 2  

winterOatPea_2026 <- winterOatPea_2026_2 %>% 
  left_join(df) %>% 
  ungroup() ## join the df with the original 

# Randomly assign if the first or second plot in the pair is the monocrop or intercrop

winterOatPea_2026_3 <-  winterOatPea_2026 %>% 
  mutate("SN" = seq(1:nrow(winterOatPea_2026))) %>% 
  group_by(SN) %>% 
  mutate("random" = runif(1)) %>% 
  ungroup() %>% 
  mutate("intercrop" = if_else(count==1,"intercrop","monocrop")) %>% 
  arrange(pairNo,random) %>%
  mutate("plotNo" = seq(1:nrow(winterOatPea_2026))) %>%  ## add the plot numbers 
  select(plotNo,pairNo,nPlots,block,accession_name,intercrop,category,seedlot_name,) %>% 
  
  mutate(accession_name=dplyr::if_else(accession_name == "BLAZE_mono", "NO_OAT_PLANTED", accession_name)) %>% 
  mutate(accession_name=dplyr::if_else(accession_name == "BLAZE_biomass", "NO_OAT_PLANTED", accession_name)) %>% 
  
  mutate(crop=dplyr::if_else(grepl("NO_OAT_PLANTED", accession_name), "Pea", "Oat")) %>% 


  mutate(intercrop = if_else(crop=="Pea","monocrop",intercrop)) %>%
  mutate("crop_2" = if_else(crop=="Oat" & intercrop == "monocrop","oat",
                            if_else(crop =="Oat" & intercrop == "monocrop", "oat",
                                    if_else(crop == "Pea", "pea", 
                                            if_else(crop=="Oat" & intercrop == "intercrop","oat-pea","na"))))) %>% ### add oat, pea, oat-pea designation 
  
  mutate(intercrop_accession_name = if_else(crop_2 == "oat-pea", "BLAZE", NA)) %>% 
  mutate(intercrop_accession_name = if_else(accession_name == "NO_OAT_PLANTED", "BLAZE", intercrop_accession_name)) %>% 
  mutate(intercrop_accession_name = if_else(intercrop_accession_name == "BLAZE" & category == "Keystone_Pea_Test", "KEYSTONE", intercrop_accession_name))



```





```{r}
winterOatPea_2026_4 <- winterOatPea_2026_3 %>% 
  left_join(read.csv(here::here("data","WOP_2026_entry.csv")), join_by(accession_name))
```


### Take a look
```{r}

print(winterOatPea_2026_4, n= nrow(winterOatPea_2026_4)) 


winterOatPea_2026_4


```



#  Save it
```{r}
# write.csv(winterOatPea_2026_4, here::here("data","WOP_2026_randomization.csv"))
```




